a=read.csv('./optiBET.csv',sep = " ",header = 0)
b=read.csv('./ROBEX.csv',sep = " ",header = 0)
c=read.csv('./FSL_BET.csv',sep = " ",header = 0)
d=read.csv('./FSL_FLIRT.csv',sep = " ",header = 0)
e=read.csv('./AFNI.csv',sep = " ",header = 0)
f=read.csv('./ANTS.csv',sep = " ",header = 0)
g=read.csv('./HD-BET.csv',sep = " ",header = 0)
h=read.csv('./MONSTR.csv',sep = " ",header = 0)
i=read.csv('./DeepMRSeg.csv',sep = " ",header = 0)
j=read.csv('./optiBET_patient_dif.csv',sep = " ",header = 0)
k=read.csv('./ROBEX_patient_dif.csv',sep = " ",header = 0)
l=read.csv('./FSL_BET_patient_dif.csv',sep = " ",header = 0)
m=read.csv('./FSL_FLIRT_patient_dif.csv',sep = " ",header = 0)
n=read.csv('./AFNI_patient_dif.csv',sep = " ",header = 0)
o=read.csv('./ANTS_patient_dif.csv',sep = " ",header = 0)
p=read.csv('./HD-BET_patient_dif.csv',sep = " ",header = 0)
q=read.csv('./MONSTR_patient_dif.csv',sep = " ",header = 0)
r=read.csv('./DeepMRSeg_patient_dif.csv',sep = " ",header = 0)
s=read.csv('./optiBET_FLIRT.csv',sep = " ",header = 0)
t=read.csv('./ROBEX_FLIRT.csv',sep = " ",header = 0)
u=read.csv('./FSL_BET_FLIRT.csv',sep = " ",header = 0)
v=read.csv('./AFNI_FLIRT.csv',sep = " ",header = 0)
w=read.csv('./ANTS_FLIRT.csv',sep = " ",header = 0)
x=read.csv('./HD-BET_FLIRT.csv',sep = " ",header = 0)
y=read.csv('./MONSTR_FLIRT.csv',sep = " ",header = 0)
z=read.csv('./DeepMRSeg_FLIRT.csv',sep = " ",header = 0)
aa=read.csv('./MONSTR_3.csv',sep = " ",header = 0)
bb=read.csv('./MONSTR_3_patient_dif.csv',sep = " ",header = 0)
cc=read.csv('./MONSTR_3_FLIRT.csv',sep = " ",header = 0)

optiBET<-c(a$V2)
ROBEX<-c(b$V2)
FSL_BET<-c(c$V2)
FSL_FLIRT<-c(d$V2)
AFNI<-c(e$V2)
ANTS<-c(f$V2)
HD_BET<-c(g$V2)
MONSTR<-c(h$V2)
DeepMRSeg<-c(i$V2)
optiBET_dif<-c(j$V1)
ROBEX_dif<-c(k$V1)
FSL_BET_dif<-c(l$V1)
FSL_FLIRT_dif<-c(m$V1)
AFNI_dif<-c(n$V1)
ANTS_dif<-c(o$V1)
HD_BET_dif<-c(p$V1)
MONSTR_dif<-c(q$V1)
DeepMRSeg_dif<-c(r$V1)
optiBET_flirt<-c(s$V1)
ROBEX_flirt<-c(t$V1)
FSL_BET_flirt<-c(u$V1)
AFNI_flirt<-c(v$V1)
ANTS_flirt<-c(w$V1)
HD_BET_flirt<-c(x$V1)
MONSTR_flirt<-c(y$V1)
DeepMRSeg_flirt<-c(z$V1)
MONSTR_2<-c(aa$V2)
MONSTR_2_dif<-c(bb$V1)
MONSTR_2_flirt<-c(cc$V1)

BET.frame<-data.frame(optiBET,ROBEX,FSL_BET,FSL_FLIRT,AFNI,ANTS,HD_BET,MONSTR,DeepMRSeg,MONSTR_2)
BET_dif.frame<-data.frame(optiBET_dif,ROBEX_dif,FSL_BET_dif,FSL_FLIRT_dif,AFNI_dif,ANTS_dif,HD_BET_dif,MONSTR_dif,DeepMRSeg_dif,MONSTR_2_dif)
BET_flirt.frame<-data.frame(optiBET_flirt,ROBEX_flirt,FSL_BET_flirt,AFNI_flirt,ANTS_flirt,HD_BET_flirt,MONSTR_flirt,DeepMRSeg_flirt,MONSTR_2_flirt)
BET_top3.frame<-data.frame(HD_BET,MONSTR,DeepMRSeg)
Bet_dif_top3.frame<-data.frame(HD_BET_dif,MONSTR_dif,DeepMRSeg_dif)
cor_plot<-cor(BET.frame)
cor_plot
library(corrplot)
corrplot(cor_plot)
cor_flirt<-c(cor(optiBET,FSL_FLIRT),cor(ROBEX,FSL_FLIRT),cor(FSL_BET,FSL_FLIRT),cor(AFNI,FSL_FLIRT),cor(ANTS,FSL_FLIRT),cor(HD_BET,FSL_FLIRT),cor(MONSTR,FSL_FLIRT),cor(DeepMRSeg,FSL_FLIRT),cor(MONSTR_2,FSL_FLIRT))
barplot(cor_flirt,xlab="Bet Method",ylab="Correlation",names.arg=c("optiBET","ROBEX","FSL_BET","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Correlation Between Bet Method and FLIRT ICV",cex.names=0.5)

plot(FSL_FLIRT,optiBET)
abline(lm(FSL_FLIRT~optiBET))
abline(1,1,col="blue")
lm(FSL_FLIRT~optiBET)
(cor(FSL_FLIRT,optiBET))^2
plot(FSL_FLIRT,ROBEX)
abline(lm(FSL_FLIRT~ROBEX))
abline(1,1,col="blue")
lm(FSL_FLIRT~ROBEX)
(cor(FSL_FLIRT,ROBEX))^2
plot(FSL_FLIRT,FSL_BET)
abline(lm(FSL_FLIRT~FSL_BET))
abline(1,1,col="blue")
lm(FSL_FLIRT~FSL_BET)
(cor(FSL_FLIRT,FSL_BET))^2
plot(FSL_FLIRT,AFNI)
abline(lm(FSL_FLIRT~AFNI))
abline(1,1,col="blue")
lm(FSL_FLIRT~AFNI)
(cor(FSL_FLIRT,AFNI))^2
plot(FSL_FLIRT,ANTS)
abline(lm(FSL_FLIRT~ANTS))
abline(1,1,col="blue")
lm(FSL_FLIRT~ANTS)
(cor(FSL_FLIRT,ANTS))^2
plot(FSL_FLIRT,HD_BET)
abline(lm(FSL_FLIRT~HD_BET))
abline(1,1,col="blue")
lm(FSL_FLIRT~HD_BET)
(cor(FSL_FLIRT,HD_BET))^2
plot(FSL_FLIRT,MONSTR)
abline(lm(FSL_FLIRT~MONSTR))
abline(1,1,col="blue")
lm(FSL_FLIRT~MONSTR)
(cor(FSL_FLIRT,MONSTR))^2
plot(FSL_FLIRT,DeepMRSeg)
abline(lm(FSL_FLIRT~DeepMRSeg))
abline(1,1,col="blue")
lm(FSL_FLIRT~DeepMRSeg)
(cor(FSL_FLIRT,DeepMRSeg))^2
plot(FSL_FLIRT,MONSTR_2)
abline(lm(FSL_FLIRT~MONSTR_2))
abline(1,1,col="blue")
lm(FSL_FLIRT~MONSTR_2)
(cor(FSL_FLIRT,MONSTR_2))^2
plot(HD_BET,MONSTR,xlim = c(1000000,2000000),ylim = c(1000000,2000000),main="Correlation Between HD-BET and MONSTR",xlab="HD-BET ICV",ylab="MONSTR ICV")
grid(nx=20,ny=20,lwd=2)
abline(lm(HD_BET~MONSTR))
abline(1,1,col="blue")
lm(HD_BET~MONSTR)
text(paste("Correlation:", round(cor(HD_BET,MONSTR),3)), x=1200000, y=1800000)
(cor(HD_BET,MONSTR))^2
plot(HD_BET,DeepMRSeg,xlim = c(1000000,2000000),ylim = c(1000000,2000000),main="Correlation Between HD-BET and DeepMRSeg",xlab="HD-BET ICV",ylab="DeepMRSeg ICV")
grid(nx=20,ny=20,lwd=2)
abline(lm(HD_BET~DeepMRSeg))
abline(1,1,col="blue")
lm(HD_BET~DeepMRSeg)
text(paste("Correlation:", round(cor(HD_BET,DeepMRSeg),3)), x=1200000, y=1800000)
(cor(HD_BET,DeepMRSeg))^2
plot(MONSTR,DeepMRSeg,xlim = c(1000000,2000000),ylim = c(1000000,2000000),main="Correlation Between MONSTR and DeepMRSeg",xlab="MONSTR ICV",ylab="DeepMRSeg ICV")
grid(nx=20,ny=20,lwd=2)
abline(lm(MONSTR~DeepMRSeg))
abline(1,1,col="blue")
lm(MONSTR~DeepMRSeg)
text(paste("Correlation:", round(cor(MONSTR,DeepMRSeg),3)), x=1200000, y=1800000)
(cor(MONSTR,DeepMRSeg))^2

median(a$V2)
median(b$V2)
median(c$V2)
median(d$V2)
median(e$V2)
median(f$V2)
median(g$V2)
median(h$V2)
median(i$V2)
median(j$V1)
median(k$V1)
median(l$V1)
median(m$V1)
median(n$V1)
median(o$V1)
median(p$V1)
median(q$V1)
median(r$V1)
median(s$V1)
median(t$V1)
median(u$V1)
median(v$V1)
median(w$V1)
median(x$V1)
median(y$V1)
median(z$V1)
median(aa$V2)
median(bb$V1)
median(cc$V1)

median_bet<-c(median(a$V2),median(b$V2),median(c$V2),median(d$V2),median(e$V2),median(f$V2),median(g$V2),median(h$V2),median(i$V2),median(aa$V2))
barplot(median_bet,xlab="Bet Method",ylab="ICV",names.arg=c("optiBET","ROBEX","FSL_BET","FSL_FLIRT","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Median ICV",cex.names=0.4)
median_dif<-c(median(j$V1),median(k$V1),median(l$V1),median(m$V1),median(n$V1),median(o$V1),median(p$V1),median(q$V1),median(r$V1),median(bb$V1))
barplot(median_dif,xlab="Bet Method",ylab="Difference",names.arg=c("optiBET","ROBEX","FSL_BET","FSL_FLIRT","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Median Test Difference",cex.names=0.4)

mean(a$V2)
mean(b$V2)
mean(c$V2)
mean(d$V2)
mean(e$V2)
mean(f$V2)
mean(g$V2)
mean(h$V2)
mean(i$V2)
mean(j$V1)
mean(k$V1)
mean(l$V1)
mean(m$V1)
mean(n$V1)
mean(o$V1)
mean(p$V1)
mean(q$V1)
mean(r$V1)
mean(aa$V2)
mean(bb$V1)

mean_bet<-c(mean(a$V2),mean(b$V2),mean(c$V2),mean(d$V2),mean(e$V2),mean(f$V2),mean(g$V2),mean(h$V2),mean(i$V2),mean(aa$V2))
barplot(mean_bet,xlab="Bet Method",ylab="ICV",names.arg=c("optiBET","ROBEX","FSL_BET","FSL_FLIRT","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Mean ICV",cex.names=0.4)
mean_dif<-c(mean(j$V1),mean(k$V1),mean(l$V1),mean(m$V1),mean(n$V1),mean(o$V1),mean(p$V1),mean(q$V1),mean(r$V1),mean(bb$V1))
barplot(mean_dif,xlab="Bet Method",ylab="Difference",names.arg=c("optiBET","ROBEX","FSL_BET","FSL_FLIRT","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Mean Test Difference",cex.names=0.4)

sd(a$V2)
sd(b$V2)
sd(c$V2)
sd(d$V2)
sd(e$V2)
sd(f$V2)
sd(g$V2)
sd(h$V2)
sd(i$V2)
sd(j$V1)
sd(k$V1)
sd(l$V1)
sd(m$V1)
sd(n$V1)
sd(o$V1)
sd(p$V1)
sd(q$V1)
sd(r$V1)
sd(aa$V2)
sd(bb$V1)
sd_bet<-c(sd(a$V2),sd(b$V2),sd(c$V2),sd(d$V2),sd(e$V2),sd(f$V2),sd(g$V2),sd(h$V2),sd(i$V2),sd(aa$V2))
barplot(sd_bet,xlab="Bet Method",ylab="ICV",names.arg=c("optiBET","ROBEX","FSL_BET","FSL_FLIRT","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Standard Deviation ICV",cex.names=0.4)
sd_dif<-c(sd(j$V1),sd(k$V1),sd(l$V1),sd(m$V1),sd(n$V1),sd(o$V1),sd(p$V1),sd(q$V1),sd(r$V1),sd(bb$V2))
barplot(sd_dif,xlab="Bet Method",ylab="Difference",names.arg=c("optiBET","ROBEX","FSL_BET","FSL_FLIRT","AFNI","ANTS","HD_BET","MONSTR","DeepMRSeg","MONSTR_2"),main="Standard Deviation Test Difference",cex.names=0.4)

boxplot(BET.frame,par(cex.axis=0.4),main="Average ICVs",xlab="Bet Method",ylab="ICV")
boxplot(BET_dif.frame,par(cex.axis=0.3),main="Average Test Differences",xlab="Bet Method",ylab="Difference")
boxplot(Bet_dif_top3.frame,par(cex.axis=1.0),main="Average ICV Difference Between Testing Sessions",xlab="Bet Method",ylab="ICV Difference",names=c("HD_BET","MONSTR","DeepMRSeg"))
boxplot(BET_flirt.frame,par(cex.axis=0.3),main="Average Difference Between Bet Method and FLIRT ICV",xlab="Bet Method",ylab="Difference")
boxplot(BET_top3.frame,par(cex.axis=1.0),main="Average ICVs of Top Methods",xlab="Bet Method",ylab="ICV")